spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

storage:
  type: local
  local-base-dir: ./data/courseware

python:
  client:
    base-url: ${PYTHON_CLIENT_BASE_URL:http://localhost:8001}

tts:
  enabled: ${TTS_ENABLED:false}
